import 'package:get/route_manager.dart';

class Languages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'cs_Cz': {
          'start': 'Start',
          'stop': 'Stop',
          'working': 'Práce',
          'pause': 'Pauza',
          'breaking': 'Přestávka',
          'We are waiting to continue breaking.':
              'Chcete pokračovat v přestávce?',
          'We are waiting to continue working.': 'Chcete pokračovat v práci?',
          'Break is finished': 'Přestávka skončila.',
          'It is time for work.': 'Je čas pracovat',
          'Work is finished': 'Práce skončila.',
          'It is time for rest.': 'Je čas na přestávku.',
          'openSettings': 'Nastavení',
          'sync': 'Synchronizace',
          'round': 'Kolo: ',
          'settingsScreen': 'Nastavení: ',
          'user': 'Majitel',
          'nameUser': 'Jméno: ',
          'nameUserTitle': 'Jméno: ',
          'nameUserHint': 'Napiště nové jméno',
          'password': 'Heslo',
          'passwordTitle': 'Heslo',
          'passwordHint': 'Napište nové heslo',
          'rounds': 'Počet kol',
          'numberRound': 'Počet kol',
          'roundTitle': 'Počet kol',
          'roundHint': 'Napište počet kol jednoho cyklu',
          'workTime': 'Čas pro práci: ',
          'minutes': ' minut',
          'workTimeTitle': 'Čas pro práci',
          'workTimeHint': 'Napište čas k práci',
          'restTime': 'Čas přestávky: ',
          'restTimeTitle': 'Čas přestávky: ',
          'restTimeHint': 'Napište čas přestávky',
          'longRestTime': 'Čas dlouhé přestávky: ',
          'longRestTimeTitle': 'Čas dlouhé přestávky: ',
          'longRestTimeHint': 'Napište čas dlouhé přestávky',
          'warnings': 'Varování: ',
          'warningPause': 'Aktivní varování spuštěné pauzy',
          'warningTimeEndingAfterWork': 'Aktivní varování na ukončenou práci',
          'warningTimeEndingAfterBreak':
              'Aktivní varování na ukončenou přestávku',
          'durationPeriodPauseWarning':
              'Časové rozpětí varování na spuštěnou pauzu.',
          'durationPeriodPauseWarningTitle':
              'Časové rozpětí varování na spuštěnou pauzu.',
          'durationPeriodPauseWarningHint': 'Změňte rozpětí varování',
          'durationPeriodFinishedWarning': 'Časové rozpětí na ukončenou práci',
          'seconds': ' sekund',
          'durationPeriodFinishedWarningTitle':
              'Časové rozpětí na ukončenou práci',
          'durationPeriodFinishedWarningHint': 'Změňte rozpětí varování',
          'Pomodoro countdown': 'Pomodoro časovač',
          'emptyProject': 'Bez projektu, ',
          'addProject': 'Přidat projekt',
          'project': 'Projekt: ',
          'login': 'Přihlásit',
          'logout': 'Odhlásit',
          'logOutTitle': 'Odhlášení',
          'logOutQuestion': 'Skutečně chcete odhlásit?',
          'yes': 'Ano',
          'no': 'Ne',
          'loginTitle': 'Přihlášení',
          'putNameUser': 'Vlož jméno uživatele',
          'cancel': 'Zrušit',
        },
        'en_US': {
          'start': 'Start',
          'stop': 'Stop',
          'working': 'Working',
          'pause': 'Pause',
          'breaking': 'Breaking',
          'We are waiting to continue breaking.':
              'Do you want continue in breaking?',
          'We are waiting to continue working.':
              'Do you want continue in working',
          'Break is finished': 'The break is over.',
          'It is time for work.': 'Its time for work.',
          'Work is finished': 'The work is over.',
          'It is time for rest.': 'Its time for rest',
          'openSettings': 'Settings: ',
          'sync': 'Synchronization',
          'Current Round: ': 'Round',
          'settingsScreen': 'Settings: ',
          'user': 'User',
          'nameUser': 'Name: ',
          'nameUserTitle': 'Name: ',
          'nameUserHint': 'Write your name',
          'password': 'Password',
          'passwordTitle': 'Password',
          'passwordHint': 'Write new password.',
          'rounds': 'Number of rounds',
          'numberRound': 'Number of rounds',
          'roundTitle': 'Number of rounds',
          'roundHint': 'Write number of rounds',
          'workTime': 'Time for work: ',
          'minutes': ' minutes',
          'workTimeTitle': 'Time for work',
          'workTimeHint': 'Write time for work',
          'restTime': 'Break time',
          'restTimeTitle': 'Break time',
          'restTimeHint': 'Write break time',
          'longRestTime': 'Long break time',
          'longRestTimeTitle': 'Long break time',
          'longRestTimeHint': 'Write long break time.',
          'warnings': 'Warnings: ',
          'warningPause': 'Active warning pause continues',
          'warningTimeEndingAfterWork': 'Active warning after work ending',
          'warningTimeEndingAfterBreak': 'Active warning after break ending',
          'durationPeriodPauseWarning': 'Duration period pause warning',
          'durationPeriodPauseWarningTitle': 'Duration period pause warning',
          'durationPeriodPauseWarningHint': 'Change duration period.',
          'durationPeriodFinishedWarning': 'Duration period finished warning',
          'seconds': 'seconds',
          'durationPeriodFinishedWarningTitle':
              'Duration perioad finished warning',
          'durationPeriodFinishedWarningHint': 'Change duration period.',
          'Pomodoro countdown': 'Pomodoro countdown',
          'emptyProject': 'Empty project, ',
          'addProject': 'Add project',
          'project': 'Project: ',
          'login': 'Login',
          'logout': 'Logout',
          'logOutTitle': 'Login',
          'logOutQuestion': 'Do you want logout?',
          'yes': 'Yes',
          'no': 'No',
          'loginTitle': 'Login',
          'putNameUser': 'Put name user',
          'cancel': 'Cancel',
        }
      };
}
