import 'package:get/route_manager.dart';

class Languages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'cs_Cz': {
          'start': 'Start',
          'stop': 'Stop',
          'working': 'Práce',
          'pause': 'Pauza',
          'breaking': 'Přestávka',
          'We are waiting to continue breaking.':
              'Chcete pokračovat v přestávce?',
          'We are waiting to continue working.': 'Chcete pokračovat v práci?',
          'Break is finished': 'Přestávka skončila.',
          'It is time for work.': 'Je čas pracovat',
          'Work is finished': 'Práce skončila.',
          'It is time for rest.': 'Je čas na přestávku.',
          'openSettings': 'Nastavení',
          'sync': 'Synchronizace',
          'round': 'Kolo: ',
          'settingsScreen': 'Nastavení: ',
          'owner': 'Majitel',
          'nameOwner': 'Jméno: ',
          'nameOwnerTitle': 'Jméno: ',
          'nameOwnerHint': 'Napiště nové jméno',
          'password': 'Heslo',
          'passwordTitle': 'Heslo',
          'passwordHint': 'Napište nové heslo',
          'rounds': 'Počet kol',
          'numberRound': 'Počet kole',
          'roundTitle': 'Počet kol',
          'roundHint': 'Napište počet kol jednoho cyklu',
          'workTime': 'Čas pro práci: ',
          'minutes': ' minut',
          'workTimeTitle': 'Čas pro práci',
          'workTimeHint': 'Napište čas k práci',
          'restTime': 'Čas přestávky: ',
          'restTimeTitle': 'Čas přestávky: ',
          'restTimeHint': 'Napište čas přestávky',
          'longRestTime': 'Čas dlouhé přestávky: ',
          'longRestTimeTitle': 'Čas dlouhé přestávky: ',
          'longRestTimeHint': 'Napište čas dlouhé přestávky',
          'warnings': 'Varování: ',
          'warningPause': 'Aktivní varování spuštěné pauzy',
          'warningTimeEndingAfterWork': 'Aktivní varování na ukončenou práci',
          'warningTimeEndingAfterBreak':
              'Aktivní varování na ukončenou přestávku',
          'durationPeriodPauseWarning':
              'Časové rozpětí varování na spuštěnou pauzu.',
          'durationPeriodPauseWarningTitle':
              'Časové rozpětí varování na spuštěnou pauzu.',
          'durationPeriodPauseWarningHint': 'Změňte rozpětí varování',
          'durationPeriodFinishedWarning': 'Časové rozpětí na ukončenou práci',
          'seconds': ' sekund',
          'durationPeriodFinishedWarningTitle':
              'Časové rozpětí na ukončenou práci',
          'durationPeriodFinishedWarningHint': 'Změňte rozpětí varování',
          'Pomodoro countdown': 'Pomodoro časovač',
          'emptyProject': 'Bez projektu, ',
          'addProject': 'Přidat projekt',
          'project': 'Projekt: '
        },
        'en_US': {
          'start': '',
          'stop': '',
          'working': '',
          'pause': '',
          'breaking': '',
          'We are waiting to continue breaking.': '',
          'We are waiting to continue working.': '',
          'Break is finished': '',
          'It is time for work.': '',
          'Work is finished': '',
          'It is time for rest.': '',
          'openSettings': '',
          'sync': '',
          'Current Round: ': '',
          'settingsScreen': '',
          'owner': '',
          'nameOwner': '',
          'nameOwnerTitle': '',
          'nameOwnerHint': '',
          'password': '',
          'passwordTitle': '',
          'passwordHint': '',
          'rounds': '',
          'numberRound': '',
          'roundTitle': '',
          'roundHint': '',
          'workTime': '',
          'minutes': '',
          'workTimeTitle': '',
          'workTimeHint': '',
          'restTime': '',
          'restTimeTitle': '',
          'restTimeHint': '',
          'longRestTime': '',
          'longRestTimeTitle': '',
          'longRestTimeHint': '',
          'warnings': '',
          'warningPause': '',
          'warningTimeEndingAfterWork': '',
          'warningTimeEndingAfterBreak': '',
          'durationPeriodPauseWarning': '',
          'durationPeriodPauseWarningTitle': '',
          'durationPeriodPauseWarningHint': '',
          'durationPeriodFinishedWarning': '',
          'seconds': '',
          'durationPeriodFinishedWarningTitle': '',
          'durationPeriodFinishedWarningHint': '',
          'Pomodoro countdown': '',
        }
      };
}
